import Head from 'next/head'
import Image from 'next/image'
import Board from '/components/Board'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-1 justify-center items-center'>
        <Board
          className='self-center grid grid-rows-3'
        >
          
          hello
        </Board>
      </main>

      <footer className=''>
      </footer>
    </div>
  )
}
